// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vineforceTask.DatabaseConnect;

#nullable disable

namespace vineforceTask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vineforceTask.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("vineforceTask.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer1@example.com",
                            CustomerName = "Customer 1",
                            CustomerPhone = "9107654321",
                            ProductId = 1,
                            Quantity = 2,
                            ShippingAddress = "House No. 1, Sector 6, Sample City, Haryana - 121002",
                            Status = 1,
                            TotalAmount = 23998m,
                            UnitPrice = 11999m,
                            UserId = "USR-2D5CA79E"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer2@example.com",
                            CustomerName = "Customer 2",
                            CustomerPhone = "9115308642",
                            ProductId = 2,
                            Quantity = 3,
                            ShippingAddress = "House No. 2, Sector 7, Sample City, Haryana - 121003",
                            Status = 2,
                            TotalAmount = 3897m,
                            UnitPrice = 1299m,
                            UserId = "USR-D9A0D80B"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer3@example.com",
                            CustomerName = "Customer 3",
                            CustomerPhone = "9122962963",
                            ProductId = 3,
                            Quantity = 1,
                            ShippingAddress = "House No. 3, Sector 8, Sample City, Haryana - 121004",
                            Status = 3,
                            TotalAmount = 1699m,
                            UnitPrice = 1699m,
                            UserId = "USR-9DA86BD2"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer4@example.com",
                            CustomerName = "Customer 4",
                            CustomerPhone = "9130617284",
                            ProductId = 4,
                            Quantity = 2,
                            ShippingAddress = "House No. 4, Sector 9, Sample City, Haryana - 121005",
                            Status = 4,
                            TotalAmount = 105980m,
                            UnitPrice = 52990m,
                            UserId = "USR-F53CBADB"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer5@example.com",
                            CustomerName = "Customer 5",
                            CustomerPhone = "9138271605",
                            ProductId = 5,
                            Quantity = 3,
                            ShippingAddress = "House No. 5, Sector 10, Sample City, Haryana - 121006",
                            Status = 0,
                            TotalAmount = 7497m,
                            UnitPrice = 2499m,
                            UserId = "USR-4C1B9CBE"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer6@example.com",
                            CustomerName = "Customer 6",
                            CustomerPhone = "9145925926",
                            ProductId = 6,
                            Quantity = 1,
                            ShippingAddress = "House No. 6, Sector 11, Sample City, Haryana - 121007",
                            Status = 1,
                            TotalAmount = 899m,
                            UnitPrice = 899m,
                            UserId = "USR-BF902AFD"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer7@example.com",
                            CustomerName = "Customer 7",
                            CustomerPhone = "9153580247",
                            ProductId = 7,
                            Quantity = 2,
                            ShippingAddress = "House No. 7, Sector 12, Sample City, Haryana - 121008",
                            Status = 2,
                            TotalAmount = 1598m,
                            UnitPrice = 799m,
                            UserId = "USR-0F393EAC"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer8@example.com",
                            CustomerName = "Customer 8",
                            CustomerPhone = "9161234568",
                            ProductId = 8,
                            Quantity = 3,
                            ShippingAddress = "House No. 8, Sector 13, Sample City, Haryana - 121009",
                            Status = 3,
                            TotalAmount = 19485m,
                            UnitPrice = 6495m,
                            UserId = "USR-C2D04583"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer9@example.com",
                            CustomerName = "Customer 9",
                            CustomerPhone = "9168888889",
                            ProductId = 9,
                            Quantity = 1,
                            ShippingAddress = "House No. 9, Sector 14, Sample City, Haryana - 121010",
                            Status = 4,
                            TotalAmount = 1099m,
                            UnitPrice = 1099m,
                            UserId = "USR-811400D1"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer10@example.com",
                            CustomerName = "Customer 10",
                            CustomerPhone = "9176543210",
                            ProductId = 10,
                            Quantity = 2,
                            ShippingAddress = "House No. 10, Sector 15, Sample City, Haryana - 121011",
                            Status = 0,
                            TotalAmount = 3598m,
                            UnitPrice = 1799m,
                            UserId = "USR-9228F6FE"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer11@example.com",
                            CustomerName = "Customer 11",
                            CustomerPhone = "9184197531",
                            ProductId = 11,
                            Quantity = 3,
                            ShippingAddress = "House No. 11, Sector 16, Sample City, Haryana - 121012",
                            Status = 1,
                            TotalAmount = 3897m,
                            UnitPrice = 1299m,
                            UserId = "USR-D5AC564F"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer12@example.com",
                            CustomerName = "Customer 12",
                            CustomerPhone = "9191851852",
                            ProductId = 12,
                            Quantity = 1,
                            ShippingAddress = "House No. 12, Sector 17, Sample City, Haryana - 121013",
                            Status = 2,
                            TotalAmount = 2599m,
                            UnitPrice = 2599m,
                            UserId = "USR-F6A013A8"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer13@example.com",
                            CustomerName = "Customer 13",
                            CustomerPhone = "9199506173",
                            ProductId = 13,
                            Quantity = 2,
                            ShippingAddress = "House No. 13, Sector 18, Sample City, Haryana - 121014",
                            Status = 3,
                            TotalAmount = 6998m,
                            UnitPrice = 3499m,
                            UserId = "USR-B9614A5A"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer14@example.com",
                            CustomerName = "Customer 14",
                            CustomerPhone = "9207160494",
                            ProductId = 14,
                            Quantity = 3,
                            ShippingAddress = "House No. 14, Sector 19, Sample City, Haryana - 121015",
                            Status = 4,
                            TotalAmount = 5685m,
                            UnitPrice = 1895m,
                            UserId = "USR-2211662B"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer15@example.com",
                            CustomerName = "Customer 15",
                            CustomerPhone = "9214814815",
                            ProductId = 15,
                            Quantity = 1,
                            ShippingAddress = "House No. 15, Sector 20, Sample City, Haryana - 121016",
                            Status = 0,
                            TotalAmount = 1799m,
                            UnitPrice = 1799m,
                            UserId = "USR-CB341CB4"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer16@example.com",
                            CustomerName = "Customer 16",
                            CustomerPhone = "9222469136",
                            ProductId = 16,
                            Quantity = 2,
                            ShippingAddress = "House No. 16, Sector 21, Sample City, Haryana - 121017",
                            Status = 1,
                            TotalAmount = 1398m,
                            UnitPrice = 699m,
                            UserId = "USR-D4BC450A"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer17@example.com",
                            CustomerName = "Customer 17",
                            CustomerPhone = "9230123457",
                            ProductId = 17,
                            Quantity = 3,
                            ShippingAddress = "House No. 17, Sector 22, Sample City, Haryana - 121018",
                            Status = 2,
                            TotalAmount = 4197m,
                            UnitPrice = 1399m,
                            UserId = "USR-7BD4E559"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer18@example.com",
                            CustomerName = "Customer 18",
                            CustomerPhone = "9237777778",
                            ProductId = 18,
                            Quantity = 1,
                            ShippingAddress = "House No. 18, Sector 23, Sample City, Haryana - 121019",
                            Status = 3,
                            TotalAmount = 599m,
                            UnitPrice = 599m,
                            UserId = "USR-40417B0F"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer19@example.com",
                            CustomerName = "Customer 19",
                            CustomerPhone = "9245432099",
                            ProductId = 19,
                            Quantity = 2,
                            ShippingAddress = "House No. 19, Sector 24, Sample City, Haryana - 121020",
                            Status = 4,
                            TotalAmount = 698m,
                            UnitPrice = 349m,
                            UserId = "USR-9814BA8A"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "customer20@example.com",
                            CustomerName = "Customer 20",
                            CustomerPhone = "9253086420",
                            ProductId = 20,
                            Quantity = 3,
                            ShippingAddress = "House No. 20, Sector 25, Sample City, Haryana - 121021",
                            Status = 0,
                            TotalAmount = 2697m,
                            UnitPrice = 899m,
                            UserId = "USR-9AA5D3CD"
                        });
                });

            modelBuilder.Entity("vineforceTask.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazorpayOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazorpayPaymentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazorpaySignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("vineforceTask.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6.6\" display, 6000mAh battery, 50MP camera",
                            ImageUrl = "https://placehold.co/600x600?text=Galaxy+M14",
                            IsActive = true,
                            Name = "Samsung Galaxy M14 5G",
                            Price = 11999m,
                            ProductUrl = "https://www.amazon.in/s?k=Samsung+Galaxy+M14+5G",
                            Sku = "SKU-ELEC-001",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "True wireless earbuds, 42H playback",
                            ImageUrl = "https://placehold.co/600x600?text=Airdopes+141",
                            IsActive = true,
                            Name = "boAt Airdopes 141",
                            Price = 1299m,
                            ProductUrl = "https://www.boat-lifestyle.com/products/airdopes-141",
                            Sku = "SKU-ELEC-002",
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "18W fast charging power bank",
                            ImageUrl = "https://placehold.co/600x600?text=Mi+Power+Bank",
                            IsActive = true,
                            Name = "Mi Power Bank 3i 20000mAh",
                            Price = 1699m,
                            ProductUrl = "https://in.event.mi.com/in/power-banks",
                            Sku = "SKU-ELEC-003",
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "15.6\" FHD display, Windows 11",
                            ImageUrl = "https://placehold.co/600x600?text=HP+15s+Laptop",
                            IsActive = true,
                            Name = "HP 15s Laptop (i5, 8GB, 512GB SSD)",
                            Price = 52990m,
                            ProductUrl = "https://www.amazon.in/s?k=HP+15s+i5+8GB+512GB+SSD",
                            Sku = "SKU-ELEC-004",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1.72\" AMOLED display, Bluetooth calling",
                            ImageUrl = "https://placehold.co/600x600?text=ColorFit+Pro+4",
                            IsActive = true,
                            Name = "Noise ColorFit Pro 4 Smartwatch",
                            Price = 2499m,
                            ProductUrl = "https://www.amazon.in/s?k=Noise+ColorFit+Pro+4",
                            Sku = "SKU-ELEC-005",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1500W, auto shut-off, stainless steel body",
                            ImageUrl = "https://placehold.co/600x600?text=Prestige+Kettle",
                            IsActive = true,
                            Name = "Prestige Electric Kettle 1.5L",
                            Price = 899m,
                            ProductUrl = "https://www.amazon.in/s?k=Prestige+Electric+Kettle+1.5L",
                            Sku = "SKU-HOME-001",
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "24-hour hot/cold insulated flask",
                            ImageUrl = "https://placehold.co/600x600?text=Milton+Flask",
                            IsActive = true,
                            Name = "Milton Thermosteel Flask 1L",
                            Price = 799m,
                            ProductUrl = "https://www.amazon.in/s?k=Milton+Thermosteel+Flask+1L",
                            Sku = "SKU-HOME-002",
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "4.1L capacity, rapid air technology",
                            ImageUrl = "https://placehold.co/600x600?text=Philips+Air+Fryer",
                            IsActive = true,
                            Name = "Philips Air Fryer HD9200",
                            Price = 6495m,
                            ProductUrl = "https://www.domesticappliances.philips.co.in/products/philips-analog-4-1-ltr-airfryer-with-rapid-air-technology-hd9200-90",
                            Sku = "SKU-HOME-003",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Airtight kitchen storage containers",
                            ImageUrl = "https://placehold.co/600x600?text=Cello+Container+Set",
                            IsActive = true,
                            Name = "Cello Storage Container Set (18 pcs)",
                            Price = 1099m,
                            ProductUrl = "https://www.amazon.in/s?k=Cello+Storage+Container+Set+18+pcs",
                            Sku = "SKU-HOME-004",
                            StockQuantity = 220
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-speed 3-blade ceiling fan",
                            ImageUrl = "https://placehold.co/600x600?text=Bajaj+Ceiling+Fan",
                            IsActive = true,
                            Name = "Bajaj Ceiling Fan 1200mm",
                            Price = 1799m,
                            ProductUrl = "https://www.amazon.in/s?k=Bajaj+Ceiling+Fan+1200mm",
                            Sku = "SKU-HOME-005",
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slim fit cotton formal shirt",
                            ImageUrl = "https://placehold.co/600x600?text=Allen+Solly+Shirt",
                            IsActive = true,
                            Name = "Allen Solly Men's Formal Shirt",
                            Price = 1299m,
                            ProductUrl = "https://allensolly.abfrl.in/p/men-white-regular-fit-solid-full-sleeves-formal-shirts-39725028.html",
                            Sku = "SKU-FASH-001",
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's slim fit denim jeans",
                            ImageUrl = "https://placehold.co/600x600?text=Levis+511+Jeans",
                            IsActive = true,
                            Name = "Levi's 511 Slim Fit Jeans",
                            Price = 2599m,
                            ProductUrl = "https://levi.in/products/mens-511-slim-fit-blue-jeans-182981650",
                            Sku = "SKU-FASH-002",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight mesh running shoes",
                            ImageUrl = "https://placehold.co/600x600?text=Puma+Running+Shoes",
                            IsActive = true,
                            Name = "Puma Men's Running Shoes",
                            Price = 3499m,
                            ProductUrl = "https://in.puma.com/in/en/mens/mens-sport/mens-sport-running",
                            Sku = "SKU-FASH-003",
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stainless steel strap, water resistant",
                            ImageUrl = "https://placehold.co/600x600?text=Fastrack+Watch",
                            IsActive = true,
                            Name = "Fastrack Analog Watch for Men",
                            Price = 1895m,
                            ProductUrl = "https://www.fastrack.in/shop/analog-watches",
                            Sku = "SKU-FASH-004",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Water-resistant laptop backpack",
                            ImageUrl = "https://placehold.co/600x600?text=Wildcraft+Backpack",
                            IsActive = true,
                            Name = "Wildcraft Backpack 30L",
                            Price = 1799m,
                            ProductUrl = "https://www.amazon.in/s?k=Wildcraft+Backpack+30L",
                            Sku = "SKU-FASH-005",
                            StockQuantity = 170
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6mm thick, non-slip surface",
                            ImageUrl = "https://placehold.co/600x600?text=Yoga+Mat",
                            IsActive = true,
                            Name = "Amazon Basics Yoga Mat",
                            Price = 699m,
                            ProductUrl = "https://www.amazon.in/s?k=Amazon+Basics+Yoga+Mat+6mm",
                            Sku = "SKU-SPRT-001",
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Home gym dumbbell set with rods",
                            ImageUrl = "https://placehold.co/600x600?text=Dumbbell+Set",
                            IsActive = true,
                            Name = "Kore PVC Dumbbell Set 10kg",
                            Price = 1399m,
                            ProductUrl = "https://www.amazon.in/s?k=Kore+PVC+Dumbbell+Set+10kg",
                            Sku = "SKU-SPRT-002",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Synthetic leather match football",
                            ImageUrl = "https://placehold.co/600x600?text=Nivia+Football",
                            IsActive = true,
                            Name = "Nivia Football Size 5",
                            Price = 599m,
                            ProductUrl = "https://www.amazon.in/s?k=Nivia+Football+Size+5",
                            Sku = "SKU-SPRT-003",
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable speed skipping rope",
                            ImageUrl = "https://placehold.co/600x600?text=Skipping+Rope",
                            IsActive = true,
                            Name = "Strauss Skipping Rope",
                            Price = 349m,
                            ProductUrl = "https://www.amazon.in/s?k=Strauss+Skipping+Rope",
                            Sku = "SKU-SPRT-004",
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2 rackets + 3 shuttlecocks combo",
                            ImageUrl = "https://placehold.co/600x600?text=Badminton+Set",
                            IsActive = true,
                            Name = "Cosco Badminton Racket Set",
                            Price = 899m,
                            ProductUrl = "https://www.amazon.in/s?k=Cosco+Badminton+Racket+Set",
                            Sku = "SKU-SPRT-005",
                            StockQuantity = 140
                        });
                });

            modelBuilder.Entity("vineforceTask.Models.Order", b =>
                {
                    b.HasOne("vineforceTask.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("vineforceTask.Models.Payment", b =>
                {
                    b.HasOne("vineforceTask.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("vineforceTask.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("vineforceTask.Models.Order", b =>
                {
                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
